Name: Sahara Khan
Student ID: 2331442

Task 1 

In [2]:
def convert_length(value, conversion_type):
    """
    Converts between meters and feet based on the conversion type.
    
    Parameters:
    value (float): The value to be converted.
    conversion_type (str): The type of conversion ("m_to_ft" or "ft_to_m").
    
    Returns:
    float: The converted value.
    """
    if conversion_type == "m_to_ft":
        return value * 3.28084  # 1 meter = 3.28084 feet
    elif conversion_type == "ft_to_m":
        return value / 3.28084  # 1 foot = 0.3048 meters
    else:
        raise ValueError("Unsupported conversion type for length")

def convert_weight(value, conversion_type):
    """
    Converts between kilograms and pounds based on the conversion type.
    
    Parameters:
    value (float): The value to be converted.
    conversion_type (str): The type of conversion ("kg_to_lbs" or "lbs_to_kg").
    
    Returns:
    float: The converted value.
    """
    if conversion_type == "kg_to_lbs":
        return value * 2.20462  # 1 kilogram = 2.20462 pounds
    elif conversion_type == "lbs_to_kg":
        return value / 2.20462  # 1 pound = 0.453592 kilograms
    else:
        raise ValueError("Unsupported conversion type for weight")

def convert_volume(value, conversion_type):
    """
    Converts between liters and gallons based on the conversion type.
    
    Parameters:
    value (float): The value to be converted.
    conversion_type (str): The type of conversion ("L_to_gal" or "gal_to_L").
    
    Returns:
    float: The converted value.
    """
    if conversion_type == "L_to_gal":
        return value * 0.264172  # 1 liter = 0.264172 gallons
    elif conversion_type == "gal_to_L":
        return value / 0.264172  # 1 gallon = 3.78541 liters
    else:
        raise ValueError("Unsupported conversion type for volume")

def main():
    print("Welcome to Sahara Unit Converter!")

    # Choose conversion type
    print("Choose a conversion type as per your wish:")
    print("1. Length")
    print("2. Weight")
    print("3. Volume")
    try:
        conversion_choice = int(input("Enter the number of your choice (1/2/3): "))
        if conversion_choice not in [1, 2, 3]:
            raise ValueError("Invalid option selected!")
        
        # Get value to convert
        value = float(input("Enter the value to be converted: "))
        
        if conversion_choice == 1:  # Length
            print("Choose the conversion:")
            print("1. Meters to Feet")
            print("2. Feet to Meters")
            length_choice = int(input("Enter the number of your choice (1/2): "))
            if length_choice == 1:
                result = convert_length(value, "m_to_ft")
                print(f"{value} meters is equal to {result} feet.")
            elif length_choice == 2:
                result = convert_length(value, "ft_to_m")
                print(f"{value} feet is equal to {result} meters.")
            else:
                print("Invalid choice for length conversion.")
        
        elif conversion_choice == 2:  # Weight
            print("Choose the conversion:")
            print("1. Kilograms to Pounds")
            print("2. Pounds to Kilograms")
            weight_choice = int(input("Enter the number of your choice (1/2): "))
            if weight_choice == 1:
                result = convert_weight(value, "kg_to_lbs")
                print(f"{value} kilograms is equal to {result} pounds.")
            elif weight_choice == 2:
                result = convert_weight(value, "lbs_to_kg")
                print(f"{value} pounds is equal to {result} kilograms.")
            else:
                print("Invalid choice for weight conversion.")
        
        elif conversion_choice == 3:  # Volume
            print("Choose the conversion:")
            print("1. Liters to Gallons")
            print("2. Gallons to Liters")
            volume_choice = int(input("Enter the number of your choice (1/2): "))
            if volume_choice == 1:
                result = convert_volume(value, "L_to_gal")
                print(f"{value} liters is equal to {result} gallons.")
            elif volume_choice == 2:
                result = convert_volume(value, "gal_to_L")
                print(f"{value} gallons is equal to {result} liters.")
            else:
                print("Invalid choice for volume conversion.")
        
        else:
            print("Invalid choice!")
    
    except ValueError as e:
        print(f"Error: {e}. Please ensure you input valid data.")

# Run the main function
if __name__ == "__main__":
    main()


Welcome to Sahara Unit Converter!
Choose a conversion type as per your wish:
1. Length
2. Weight
3. Volume


Enter the number of your choice (1/2/3):  2
Enter the value to be converted:  70


Choose the conversion:
1. Kilograms to Pounds
2. Pounds to Kilograms


Enter the number of your choice (1/2):  1


70.0 kilograms is equal to 154.3234 pounds.


Task 2 

In [4]:
def find_sum(numbers):
    """
    Calculates the sum of a list of numbers.
    
    Parameters:
    numbers (list): A list of numbers.
    
    Returns:
    float: The sum of the numbers.
    """
    return sum(numbers)

def find_average(numbers):
    """
    Calculates the average of a list of numbers.
    
    Parameters:
    numbers (list): A list of numbers.
    
    Returns:
    float: The average of the numbers.
    """
    if len(numbers) == 0:
        raise ValueError("The list is empty. Cannot calculate the average.")
    return sum(numbers) / len(numbers)

def find_maximum(numbers):
    """
    Finds the maximum value in a list of numbers.
    
    Parameters:
    numbers (list): A list of numbers.
    
    Returns:
    float: The maximum value in the list.
    """
    if len(numbers) == 0:
        raise ValueError("The list is empty. Cannot find the maximum.")
    return max(numbers)

def find_minimum(numbers):
    """
    Finds the minimum value in a list of numbers.
    
    Parameters:
    numbers (list): A list of numbers.
    
    Returns:
    float: The minimum value in the list.
    """
    if len(numbers) == 0:
        raise ValueError("The list is empty. Cannot find the minimum.")
    return min(numbers)

def main():
    print("Welcome to Sahara's Mathematical Operations Program!")

    # Choose operation
    print("Choose an operation:")
    print("1. Find the sum")
    print("2. Find the average")
    print("3. Find the maximum")
    print("4. Find the minimum")
    
    try:
        operation_choice = int(input("Enter the number of your choice (1/2/3/4): "))
        if operation_choice not in [1, 2, 3, 4]:
            raise ValueError("Invalid operation selected!")
        
        # Get list of numbers
        numbers_input = input("Enter a list of numbers separated by spaces: ")
        numbers = [float(num) for num in numbers_input.split()]
        
        if not numbers:
            raise ValueError("The list cannot be empty.")
        
        # Perform the selected operation
        if operation_choice == 1:
            result = find_sum(numbers)
            print(f"The sum of the numbers is: {result}")
        elif operation_choice == 2:
            result = find_average(numbers)
            print(f"The average of the numbers is: {result}")
        elif operation_choice == 3:
            result = find_maximum(numbers)
            print(f"The maximum value in the list is: {result}")
        elif operation_choice == 4:
            result = find_minimum(numbers)
            print(f"The minimum value in the list is: {result}")
    
    except ValueError as e:
        print(f"Error: {e}. Please ensure you input valid data.")

# Run the main function
if __name__ == "__main__":
    main()


Welcome to Sahara's Mathematical Operations Program!
Choose an operation:
1. Find the sum
2. Find the average
3. Find the maximum
4. Find the minimum


Enter the number of your choice (1/2/3/4):  3
Enter a list of numbers separated by spaces:  23 45 67 88 19 22 


The maximum value in the list is: 88.0


Exercise on List Manipulation:

In [6]:
#1. Extract Every Other Element:
def extract_every_other(lst):
    """
    Extracts every other element from the list, starting from the first element.
    
    Parameters:
    lst (list): A list of elements.
    
    Returns:
    list: A new list containing every other element from the original list.
    """
    return lst[::2]

# User input
user_input = input("Enter a list of numbers separated by spaces: ")

# Convert the user input string into a list of integers
input_list = [int(i) for i in user_input.split()]

# Get the result from the function
output_list = extract_every_other(input_list)

# Print the result
print("The extracted list with every other element is:", output_list)


Enter a list of numbers separated by spaces:  2 4 6 8 10


The extracted list with every other element is: [2, 6, 10]


In [8]:
#2. Slice a Sublist:
def get_sublist(lst, start, end):
    """
    Returns a sublist from the list starting from the given start index and ending at the given end index (inclusive).
    
    Parameters:
    lst (list): The list from which the sublist is to be extracted.
    start (int): The starting index for the sublist (inclusive).
    end (int): The ending index for the sublist (inclusive).
    
    Returns:
    list: A sublist from the start to end index (inclusive).
    """
    return lst[start:end+1]

# User input for the list
user_input = input("Enter a list of numbers separated by spaces: ")

# Convert the user input string into a list of integers
input_list = [int(i) for i in user_input.split()]

# User input for the start and end indices
start_index = int(input("Enter the start index: "))
end_index = int(input("Enter the end index: "))

# Get the result from the function
output_list = get_sublist(input_list, start_index, end_index)

# Print the result
print("The extracted sublist is:", output_list)


Enter a list of numbers separated by spaces:  22 20 25 26 24
Enter the start index:  1
Enter the end index:  4


The extracted sublist is: [20, 25, 26, 24]


In [9]:
#3. Reverse a List Using Slicing:
def reverse_list(lst):
    """
    Reverses the given list using slicing.
    
    Parameters:
    lst (list): The list to be reversed.
    
    Returns:
    list: The reversed list.
    """
    return lst[::-1]

# User input for the list
user_input = input("Enter a list of numbers separated by spaces: ")

# Convert the user input string into a list of integers
input_list = [int(i) for i in user_input.split()]

# Get the reversed list from the function
reversed_list = reverse_list(input_list)

# Print the reversed list
print("The reversed list is:", reversed_list)


Enter a list of numbers separated by spaces:  20 33 56 78 12 23 


The reversed list is: [23, 12, 78, 56, 33, 20]


In [10]:
#4. Remove the First and Last Elements:
def remove_first_last(lst):
    """
    Removes the first and last elements of the list and returns the resulting sublist.
    
    Parameters:
    lst (list): The list from which the first and last elements will be removed.
    
    Returns:
    list: The sublist without the first and last elements.
    """
    return lst[1:-1]

# User input for the list
user_input = input("Enter a list of numbers separated by spaces: ")

# Convert the user input string into a list of integers
input_list = [int(i) for i in user_input.split()]

# Get the sublist after removing the first and last elements
resulting_sublist = remove_first_last(input_list)

# Print the resulting sublist
print("The list after removing the first and last elements is:", resulting_sublist)


Enter a list of numbers separated by spaces:  1 2 3 4 5 17


The list after removing the first and last elements is: [2, 3, 4, 5]


In [11]:
#5. Get the First n Elements:
def get_first_n(lst, n):
    """
    Extracts the first n elements from the list using slicing.
    
    Parameters:
    lst (list): The list from which the first n elements will be extracted.
    n (int): The number of elements to extract from the beginning of the list.
    
    Returns:
    list: A list containing the first n elements.
    """
    return lst[:n]

# User input for the list
user_input = input("Enter a list of numbers separated by spaces: ")

# Convert the user input string into a list of integers
input_list = [int(i) for i in user_input.split()]

# User input for the number of elements to extract
n = int(input("Enter the number of elements to extract: "))

# Get the first n elements using the function
first_n_elements = get_first_n(input_list, n)

# Print the result
print("The first", n, "elements are:", first_n_elements)


Enter a list of numbers separated by spaces:  23 34 42 51 21
Enter the number of elements to extract:  3


The first 3 elements are: [23, 34, 42]


In [12]:
#6. Extract Elements from the End:
def get_last_n(lst, n):
    """
    Extracts the last n elements from the list using slicing.
    
    Parameters:
    lst (list): The list from which the last n elements will be extracted.
    n (int): The number of elements to extract from the end of the list.
    
    Returns:
    list: A list containing the last n elements.
    """
    return lst[-n:]

# User input for the list
user_input = input("Enter a list of numbers separated by spaces: ")

# Convert the user input string into a list of integers
input_list = [int(i) for i in user_input.split()]

# User input for the number of elements to extract
n = int(input("Enter the number of elements to extract from the end: "))

# Get the last n elements using the function
last_n_elements = get_last_n(input_list, n)

# Print the result
print("The last", n, "elements are:", last_n_elements)


Enter a list of numbers separated by spaces:  94 37 63 59 12
Enter the number of elements to extract from the end:  3


The last 3 elements are: [63, 59, 12]


In [13]:
#7. Extract Elements in Reverse Order:
def reverse_skip(lst):
    """
    Extracts every second element starting from the second-to-last element, moving backward.
    
    Parameters:
    lst (list): The list from which elements are to be extracted.
    
    Returns:
    list: A new list containing every second element starting from the second-to-last element.
    """
    return lst[-2::-2]

# User input for the list
user_input = input("Enter a list of numbers separated by spaces: ")

# Convert the user input string into a list of integers
input_list = [int(i) for i in user_input.split()]

# Get the result from the function
result_list = reverse_skip(input_list)

# Print the result
print("The extracted list in reverse order skipping one element is:", result_list)



Enter a list of numbers separated by spaces:  1 2 3 4 5 


The extracted list in reverse order skipping one element is: [4, 2]


Exercise on Nested List:

In [14]:
#1. Flatten a Nested List:
def flatten(lst):
    """
    Flattens a nested list into a single list.
    
    Parameters:
    lst (list): The nested list to be flattened.
    
    Returns:
    list: A single list containing all the elements from the nested list.
    """
    flattened_list = []
    for sublist in lst:
        # If the sublist is actually a list, extend the flattened list with its elements
        flattened_list.extend(sublist)
    return flattened_list

# User input for the nested list
user_input = input("Enter a nested list (e.g., [[1, 2], [3, 4], [5]]): ")

# Convert the input string into an actual nested list
nested_list = eval(user_input)

# Get the flattened list
flattened_result = flatten(nested_list)

# Print the result
print("The flattened list is:", flattened_result)


Enter a nested list (e.g., [[1, 2], [3, 4], [5]]):  [[2,3], [6,7], [9,8]]


The flattened list is: [2, 3, 6, 7, 9, 8]


In [15]:
#2. Accessing Nested List Elements:
def access_nested_element(lst, indices):
    """
    Extracts a specific element from a nested list given its indices.
    
    Parameters:
    lst (list): The nested list from which the element will be accessed.
    indices (list): A list of indices to access the element in the nested list.
    
    Returns:
    The element at the specified indices in the nested list.
    """
    element = lst
    for index in indices:
        element = element[index]
    return element

# User input for the nested list
user_input = input("Enter a nested list (e.g., [[1, 2, 3], [4, 5, 6], [7, 8, 9]]): ")

# Convert the input string into an actual nested list
nested_list = eval(user_input)

# User input for the list of indices
indices_input = input("Enter the indices as a list (e.g., [1, 2]): ")

# Convert the input string into a list of integers
indices = [int(i) for i in indices_input.strip('[]').split(',')]

# Get the element from the nested list using the function
element = access_nested_element(nested_list, indices)

# Print the result
print("The element at the specified indices is:", element)


Enter a nested list (e.g., [[1, 2, 3], [4, 5, 6], [7, 8, 9]]):  [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Enter the indices as a list (e.g., [1, 2]):  [2,1]


The element at the specified indices is: 8


In [16]:
#3. Sum of All Elements in a Nested List:
def sum_nested(lst):
    """
    Calculates the sum of all the numbers in a nested list, regardless of depth.
    
    Parameters:
    lst (list): The nested list containing numbers.
    
    Returns:
    int: The sum of all the elements in the nested list.
    """
    total = 0
    for element in lst:
        if isinstance(element, list):
            # Recursively call sum_nested to handle nested lists
            total += sum_nested(element)
        else:
            total += element
    return total

# User input for the nested list
user_input = input("Enter a nested list (e.g., [[1, 2], [3, [4, 5]], 6]): ")

# Convert the input string into an actual nested list
nested_list = eval(user_input)

# Get the sum of all elements in the nested list
result = sum_nested(nested_list)

# Print the result
print("The sum of all elements in the nested list is:", result)


Enter a nested list (e.g., [[1, 2], [3, [4, 5]], 6]):  [[1, 2], [3, [4, 5]], 6]


The sum of all elements in the nested list is: 21


In [17]:
#4. Remove Specific Element from a Nested List:
def remove_element(lst, elem):
    """
    Removes all occurrences of a specific element from a nested list.
    
    Parameters:
    lst (list): The nested list to remove the element from.
    elem (any): The element to remove from the list.
    
    Returns:
    list: The modified list with all occurrences of elem removed.
    """
    # Iterate over the list and handle nested lists
    for i in range(len(lst)):
        if isinstance(lst[i], list):
            # Recursively call remove_element on sublist
            lst[i] = remove_element(lst[i], elem)
        else:
            # Remove the element if found
            if lst[i] == elem:
                lst[i] = None  # Mark element for removal (temporary)

    # Remove None values (which are the marked elements) from the list
    return [x for x in lst if x is not None]

# User input for the nested list
user_input = input("Enter a nested list (e.g., [[1, 2], [3, 2], [4, 5]]): ")

# Convert the input string into an actual nested list
nested_list = eval(user_input)

# User input for the element to remove
elem = input("Enter the element to remove: ")
# Convert input to appropriate type (assuming it's a number)
elem = int(elem) if elem.isdigit() else elem

# Get the modified list after removing the element
modified_list = remove_element(nested_list, elem)

# Print the result
print("The modified list is:", modified_list)


Enter a nested list (e.g., [[1, 2], [3, 2], [4, 5]]):  [[1, 2], [3, 2], [4, 5]]
Enter the element to remove:  2


The modified list is: [[1], [3], [4, 5]]


In [18]:
#5. Find the Maximum Element in a Nested List:
def find_max(lst):
    """
    Finds the maximum element in a nested list, regardless of depth.
    
    Parameters:
    lst (list): The nested list to find the maximum element in.
    
    Returns:
    int/float: The maximum element in the nested list.
    """
    max_element = float('-inf')  # Initialize to the smallest possible value
    
    for element in lst:
        if isinstance(element, list):
            # Recursively call find_max to handle nested lists
            max_element = max(max_element, find_max(element))
        else:
            # Compare the element with the current maximum
            max_element = max(max_element, element)
    
    return max_element

# User input for the nested list
user_input = input("Enter a nested list (e.g., [[1, 2], [3, [4, 5]], 6]): ")

# Convert the input string into an actual nested list
nested_list = eval(user_input)

# Get the maximum element in the nested list
max_element = find_max(nested_list)

# Print the result
print("The maximum element in the nested list is:", max_element)


Enter a nested list (e.g., [[1, 2], [3, [4, 5]], 6]):  [[1, 2], [3, [4, 9]], 8]


The maximum element in the nested list is: 9


In [19]:
#6. Count Occurrences of an Element in a Nested List:
def count_occurrences(lst, elem):
    """
    Counts the occurrences of a specific element in a nested list.
    
    Parameters:
    lst (list): The nested list to count occurrences in.
    elem (any): The element to count occurrences of.
    
    Returns:
    int: The count of occurrences of elem in the nested list.
    """
    count = 0
    for element in lst:
        if isinstance(element, list):
            # Recursively call count_occurrences for sublist
            count += count_occurrences(element, elem)
        else:
            # If the element matches, increase the count
            if element == elem:
                count += 1
    return count

# User input for the nested list
user_input = input("Enter a nested list (e.g., [[1, 2], [2, 3], [2, 4]]): ")

# Convert the input string into an actual nested list
nested_list = eval(user_input)

# User input for the element to count
elem_input = input("Enter the element to count: ")

# Convert the input to the appropriate type
elem = int(elem_input) if elem_input.isdigit() else elem_input

# Get the count of occurrences of the element
count = count_occurrences(nested_list, elem)

# Print the result
print(f"The element {elem} appears {count} times in the nested list.")


Enter a nested list (e.g., [[1, 2], [2, 3], [2, 4]]):  [[1, 2], [2, 3], [2, 2]]
Enter the element to count:  2


The element 2 appears 4 times in the nested list.


In [20]:
#7. Flatten a List of Lists of Lists:
def deep_flatten(lst):
    """
    Flattens a deeply nested list of lists into a single list, regardless of the depth.
    
    Parameters:
    lst (list): The deeply nested list to flatten.
    
    Returns:
    list: A flattened version of the input list.
    """
    flattened = []
    for element in lst:
        if isinstance(element, list):
            # Recursively call deep_flatten for nested lists
            flattened.extend(deep_flatten(element))
        else:
            # If the element is not a list, add it to the flattened list
            flattened.append(element)
    return flattened

# User input for the deeply nested list
user_input = input("Enter a deeply nested list (e.g., [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]): ")

# Convert the input string into an actual nested list
nested_list = eval(user_input)

# Flatten the nested list
flattened_list = deep_flatten(nested_list)

# Print the flattened list
print("The flattened list is:", flattened_list)


Enter a deeply nested list (e.g., [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]):   [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]


The flattened list is: [1, 2, 3, 4, 5, 6, 7, 8]


In [25]:
#8. Nested List Average:
def average_nested(lst):
    """
    Calculates the average of all elements in a nested list.
    
    Parameters:
    lst (list): The nested list containing numeric elements.
    
    Returns:
    float: The average of all the elements in the nested list.
    """
    total_sum = 0
    total_count = 0
    
    # Iterate through each element in the nested list
    for element in lst:
        if isinstance(element, list):
            # Recursively call average_nested for sublists and get the sum and count
            sub_sum, sub_count = average_nested(element)
            total_sum += sub_sum
            total_count += sub_count
        else:
            # Add the element to total sum and increment count
            total_sum += element
            total_count += 1
    
    return total_sum, total_count  # Return both sum and count

# User input for the nested list
user_input = input("Enter a nested list (e.g., [[1, 2], [3, 4], [5, 6]]): ")

# Convert the input string into an actual nested list
nested_list = eval(user_input)

# Get the sum and count of all elements in the nested list
total_sum, total_count = average_nested(nested_list)

# Calculate the average
if total_count == 0:
    print("The list is empty.")
else:
    average = total_sum / total_count
    print("The average of all elements in the nested list is:", average)


Enter a nested list (e.g., [[1, 2], [3, 4], [5, 6]]):  [[3], [3, 4], [5, 6]]


The average of all elements in the nested list is: 4.2


To - Do - NumPy

Basic Vector and Matrix Operation with Numpy

Problem - 1: Array Creation:

In [26]:
import numpy as np

# 1. Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
print("1. Empty Array (2x2):\n", empty_array)

# 2. Initialize an all-one array with size 4x2
ones_array = np.ones((4, 2))
print("\n2. All-One Array (4x2):\n", ones_array)

# 3. Return a new array of given shape and type, filled with a fill value
fill_value_array = np.full((3, 3), 7)  # Example: 3x3 array filled with 7
print("\n3. Array filled with a value (3x3, filled with 7):\n", fill_value_array)

# 4. Return a new array of zeros with the same shape and type as a given array
sample_array = np.array([[1, 2, 3], [4, 5, 6]])  # Example array
zeros_like_array = np.zeros_like(sample_array)
print("\n4. Zeros array with same shape as sample array:\n", zeros_like_array)

# 5. Return a new array of ones with the same shape and type as a given array
ones_like_array = np.ones_like(sample_array)
print("\n5. Ones array with same shape as sample array:\n", ones_like_array)

# 6. Convert an existing list to a NumPy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\n6. Converted NumPy array from list:\n", numpy_array)


1. Empty Array (2x2):
 [[0. 0.]
 [0. 0.]]

2. All-One Array (4x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Array filled with a value (3x3, filled with 7):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

4. Zeros array with same shape as sample array:
 [[0 0 0]
 [0 0 0]]

5. Ones array with same shape as sample array:
 [[1 1 1]
 [1 1 1]]

6. Converted NumPy array from list:
 [1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

In [27]:
import numpy as np

# 1. Create an array with values ranging from 10 to 49
array_10_to_49 = np.arange(10, 50)
print("1. Array with values from 10 to 49:\n", array_10_to_49)

# 2. Create a 3x3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n2. 3x3 Matrix with values from 0 to 8:\n", matrix_3x3)

# 3. Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("\n3. 3x3 Identity Matrix:\n", identity_matrix)

# 4. Create a random array of size 30 and find the mean of the array
random_array = np.random.random(30)
mean_value = random_array.mean()
print("\n4. Mean of random array of size 30:", mean_value)

# 5. Create a 10x10 array with random values and find the minimum and maximum values
random_matrix = np.random.random((10, 10))
min_value = random_matrix.min()
max_value = random_matrix.max()
print("\n5. Minimum value:", min_value)
print("   Maximum value:", max_value)

# 6. Create a zero array of size 10 and replace 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1  # Index 4 corresponds to the 5th element
print("\n6. Zero array with 5th element replaced with 1:\n", zero_array)

# 7. Reverse an array arr = [1,2,0,0,4,0]
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\n7. Reversed array:\n", reversed_arr)

# 8. Create a 2D array with 1 on the border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n8. 2D array with 1 on border and 0 inside:\n", border_array)

# 9. Create an 8x8 matrix and fill it with a checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1  # Fill 1 at even indices of odd rows
checkerboard[::2, 1::2] = 1  # Fill 1 at odd indices of even rows
print("\n9. 8x8 Checkerboard Pattern:\n", checkerboard)


1. Array with values from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 Matrix with values from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3. 3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Mean of random array of size 30: 0.5444930066060911

5. Minimum value: 0.015323432960566152
   Maximum value: 0.9993908414140933

6. Zero array with 5th element replaced with 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

7. Reversed array:
 [0 4 0 0 2 1]

8. 2D array with 1 on border and 0 inside:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

9. 8x8 Checkerboard Pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Problem - 3: Array Operations:

In [28]:
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays
add_xy = x + y
print("1. Addition of x and y:\n", add_xy)

# 2. Subtract the two arrays
subtract_xy = x - y
print("\n2. Subtraction of x and y:\n", subtract_xy)

# 3. Multiply the array with any integer (e.g., 3)
multiply_x = x * 3
print("\n3. Multiplication of x by 3:\n", multiply_x)

# 4. Find the square of each element of the array x
square_x = np.square(x)
print("\n4. Square of each element in x:\n", square_x)

# 5. Find the dot product
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)  
dot_xy = np.dot(x, y)

print("\n5. Dot product:")
print("   v . w:", dot_vw)
print("   x . v:\n", dot_xv)
print("   x . y:\n", dot_xy)

# 6. Concatenate x and y along rows & Concatenate v and w along columns
concat_xy_row = np.concatenate((x, y), axis=0)
concat_vw_col = np.vstack((v, w))  # np.vstack() stacks along column

print("\n6. Concatenation:")
print("   Concatenation of x and y along rows:\n", concat_xy_row)
print("   Concatenation of v and w along columns:\n", concat_vw_col)

# 7. Attempt to concatenate x and v
try:
    concat_xv = np.concatenate((x, v), axis=0)  # Trying to concatenate x (2x2) and v (1x2)
    print("\n7. Concatenation of x and v:\n", concat_xv)
except ValueError as e:
    print("\n7. Error when trying to concatenate x and v:", e)



1. Addition of x and y:
 [[ 6  8]
 [10 13]]

2. Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]

3. Multiplication of x by 3:
 [[ 3  6]
 [ 9 15]]

4. Square of each element in x:
 [[ 1  4]
 [ 9 25]]

5. Dot product:
   v . w: 219
   x . v:
 [29 77]
   x . y:
 [[19 22]
 [50 58]]

6. Concatenation:
   Concatenation of x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
   Concatenation of v and w along columns:
 [[ 9 10]
 [11 12]]

7. Error when trying to concatenate x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Problem - 4: Matrix Operations:

In [29]:
import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])


In [30]:
#Prove A.A−1 = I.

A_inv = np.linalg.inv(A)  # Compute A inverse
I = np.dot(A, A_inv)  # A * A^(-1)

# Round to remove floating-point errors
I = np.round(I, decimals=10)
print("A * A_inv = \n", I)




A * A_inv = 
 [[1. 0.]
 [0. 1.]]


In [31]:
#Prove AB ̸= BA.

AB = np.dot(A, B)
BA = np.dot(B, A)

print("AB = \n", AB)
print("BA = \n", BA)
print("Are they equal? ", np.array_equal(AB, BA))


AB = 
 [[23 13]
 [51 29]]
BA = 
 [[36 44]
 [13 16]]
Are they equal?  False


In [32]:
#Prove (AB)^T = A^T .B^T
AB_T = np.transpose(np.dot(A, B))  # (AB)^T
BT_AT = np.dot(np.transpose(B), np.transpose(A))  # B^T * A^T

print("Transpose of (AB): \n", AB_T)
print("B^T * A^T: \n", BT_AT)
print("Are they equal? ", np.array_equal(AB_T, BT_AT))



Transpose of (AB): 
 [[23 51]
 [13 29]]
B^T * A^T: 
 [[23 51]
 [13 29]]
Are they equal?  True


Problem 2: Solving System of Linear Equations using Inverse Method

In [33]:
# Define the coefficient matrix A
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

# Define the constants matrix B
B = np.array([-1, -3, 9])

# Compute the inverse of A
A_inv = np.linalg.inv(A)

# Solve for X
X = np.dot(A_inv, B)

print("Solution for [x, y, z]:", X)


Solution for [x, y, z]: [ 2.  1. -2.]


In [34]:
X = np.linalg.solve(A, B)
print("Solution using np.linalg.solve:", X)


Solution using np.linalg.solve: [ 2.  1. -2.]


Experiment: How Fast is Numpy?

In [35]:
import numpy as np
import time


In [37]:
#Using Python Lists
size = 1_000_000
list1 = list(range(size))
list2 = list(range(size))

start_time = time.time()
result_list = [list1[i] + list2[i] for i in range(size)]
end_time = time.time()

print("Python Lists Addition Time:", end_time - start_time, "seconds")

#Using NumPy Arrays
array1 = np.arange(size)
array2 = np.arange(size)

start_time = time.time()
result_array = array1 + array2
end_time = time.time()

print("NumPy Arrays Addition Time:", end_time - start_time, "seconds")



Python Lists Addition Time: 0.06877279281616211 seconds
NumPy Arrays Addition Time: 0.0015239715576171875 seconds


In [38]:
#Using Python Lists
start_time = time.time()
result_list = [list1[i] * list2[i] for i in range(size)]
end_time = time.time()

print("Python Lists Multiplication Time:", end_time - start_time, "seconds")


#Using NumPy Arrays
start_time = time.time()
result_array = array1 * array2
end_time = time.time()

print("NumPy Arrays Multiplication Time:", end_time - start_time, "seconds")



Python Lists Multiplication Time: 0.10402774810791016 seconds
NumPy Arrays Multiplication Time: 0.00783681869506836 seconds


In [39]:
#Using Python Lists
start_time = time.time()
dot_product_list = sum(list1[i] * list2[i] for i in range(size))
end_time = time.time()

print("Python Lists Dot Product Time:", end_time - start_time, "seconds")

#Using NumPy Arrays
start_time = time.time()
dot_product_array = np.dot(array1, array2)
end_time = time.time()

print("NumPy Arrays Dot Product Time:", end_time - start_time, "seconds")


Python Lists Dot Product Time: 0.08055281639099121 seconds
NumPy Arrays Dot Product Time: 0.0005309581756591797 seconds


In [41]:
#Using Python Lists
size = 1000
matrix1 = [[i for i in range(size)] for j in range(size)]
matrix2 = [[j for j in range(size)] for i in range(size)]

start_time = time.time()
result_matrix = [[sum(a * b for a, b in zip(row, col)) for col in zip(*matrix2)] for row in matrix1]
end_time = time.time()

print("Python Lists Matrix Multiplication Time:", end_time - start_time, "seconds")

#Using NumPy Arrays
matrix1_np = np.arange(size * size).reshape(size, size)
matrix2_np = np.arange(size * size).reshape(size, size)

start_time = time.time()
result_matrix_np = np.dot(matrix1_np, matrix2_np)
end_time = time.time()

print("NumPy Arrays Matrix Multiplication Time:", end_time - start_time, "seconds")


Python Lists Matrix Multiplication Time: 41.93743109703064 seconds
NumPy Arrays Matrix Multiplication Time: 0.484935998916626 seconds
